# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f28aead63ac7229a638034ff0efe51ec713eeb8c47b9c681ef86c850019ab732763f40499c75bd4fa0093a0a5b5d80593ddfe39c2073877d68d8c11768611fee

test:
  secret_key_base: 87016941f8f01f821a7e267b442624f7eb541df0765aec6d781943fab5faa2c67f7d2906cb85c230c774529d2b4da9bff881da24671b432b7c6b75f98dd2f0da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
